# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html#directory-layout
---
# playbook.yml

- hosts: localhost
  connection: local
  gather_facts: yes
  become: true
  become_user: "root"
  vars_files:
    - "vars.yml"
  roles:
    - geerlingguy.firewall
    - geerlingguy.git
    - apolloclark.nano_highlighting
    - java_role
    - apolloclark.zookeeper
    - apolloclark.kafka
    - apolloclark.elasticsearch
    - apolloclark.logstash
    - apolloclark.kibana
    - apolloclark.elastalert
    - apolloclark.auditbeat
    - apolloclark.filebeat
    - apolloclark.packetbeat
    - apolloclark.metricbeat
    - apolloclark.heartbeat
    - apolloclark.osquery
    - apolloclark.crontab
